**Operations**

In [1]:
5 + 2

7

In [2]:
7 - 2

5

In [3]:
5 * 2

10

In [8]:
5 / 2

2.5

In [19]:
8 % 4

0

In [20]:
5 ** 2

25

In [24]:
(2 + 2) ** 2 / 16

1.0

**Variables**

In [25]:
x = 10

print(x ** 2)

100


In [28]:
x = 'cat'

print(x)

cat


If I want to insert something inside of 'cat' **.format()**

In [30]:
x = 'cat{}'.format('s')

print(x)

cats


In [39]:
cats = 12.2565123516212

x = 'I have {:.0f} cats'.format(cats)

print(x)

I have 12 cats


**Lists, Tuples, Dictionaries, Arrays**

*Lists*

In [110]:
x = [1, 2, 3, 20, 'cat', [1, 2, 'cats']]
y = ['dogs', 12]

print(x)

[1, 2, 3, 20, 'cat', [1, 2, 'cats']]


In [111]:
print(x*2)
print(x+y)

x.append(55)

print(x)

[1, 2, 3, 20, 'cat', [1, 2, 'cats'], 1, 2, 3, 20, 'cat', [1, 2, 'cats']]
[1, 2, 3, 20, 'cat', [1, 2, 'cats'], 'dogs', 12]
[1, 2, 3, 20, 'cat', [1, 2, 'cats'], 55]


In [70]:
print('Before: ', x[5][2])

x[5][2] = 'cat'

print('After: ', x[5][2])

Before:  cats
After:  cat


*Tuples*

In [71]:
#tuple is immutable

x = (1, 2, 3, 'cats', [1, 2])

print(x)

(1, 2, 3, 'cats', [1, 2])


In [77]:
print(x[4])

x[0] = 1 #you can't make this

[1, 2]


TypeError: 'tuple' object does not support item assignment

*Dictionary*

In [87]:
d = {'cat':'happy', 'dog':'sad', 'Kevin':20, 17:'Prime', 6:3 + 3}

print(d['cat'])
print(d['dog'])
print(d[17])
print(d[6])
print(d['Kevin'])

happy
sad
Prime
6
20


*Array*

In [117]:
import numpy as np

x = np.array([1, 2, 3, 40])

#as a vector operations

print(x)
print(2*x)
print(x**3)
print(1/x)

[ 1  2  3 40]
[ 2  4  6 80]
[    1     8    27 64000]
[1.         0.5        0.33333333 0.025     ]


There are two ways to make an array

In [123]:
x = np.linspace(0, 10, 20)
print(x)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [128]:
x = np.arange(0, 10, 1)
print(x)

[0 1 2 3 4 5 6 7 8 9]
